
global:
  resolve_timeout: 5m

route:
  receiver: 'slack'
  repeat_interval: 15m
  group_interval: 5m
  group_wait: 1m
  routes:
  - receiver: 'msteams'
    match:
      alert: msteams

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        api_url: 'https://hooks.slack.com/services/<YOUR_KEY>'
        username: 'Prometheus - Alerter'
        channel: '#<CHANNEL_NAME>'
        text: '{{ .CommonAnnotations.summary }} ---> {{ .CommonAnnotations.description }}'

  - name: "msteams"
    webhook_configs:
    - url: 'http://prom2teams:8089'
      send_resolved: false